encoding: UTF-8

# Permalinks
permalink:           pretty

# Setup
title:               Zhiguang Wang
tagline:             'Technology. Game. Art.'
description:         'Created by <a href="http://zhiguang.me" target="_blank">Zhiguang Wang</a> using <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and <a href="https://disqus.com" target="_blank">Disqus</a>, hosted on <a href="https://pages.github.com" target="_blank">Github Pages</a>.<br /><br />Theme based on <a href="http://jekyllthemes.io/theme/15489219/lanyon" target="_blank">Lanyon</a>.'
url:                 http://wang.zhiguang.me
baseurl:             ''
# paginate:            5

# About/contact
author:
  name:              Zhiguang Wang
  gravatar:          a4c746920838b12387c69bc8885296a0
  url:               http://wang.zhiguang.me
  email:             ''

# Custom vars
# version:             1.0.0

# Gems
# gems: [ jekyll-paginate ]

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
